name: "Build and release"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    # Set up the build environment
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Install nix
      uses: cachix/install-nix-action@v16

    # Build and retrieve the documents in the current directory
    - name: Build the documents
      id: nix-build
      run: nix build
    - name: Retrieve the PDF
      run: |
        cp $(nix path-info)/*.pdf .

    # Upload the PDF as job artifact
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "documents"
        path: ./*.pdf 

    # If the build failed, upload the build log instead
    - name: Retrieve build log
      if: ${{ always() && steps.nix-build.outcome == 'failure' }}
      run: nix log > build.log
    - name: Upload the build log artifact
      uses: actions/upload-artifact@v2
      if: ${{ always() && steps.nix-build.outcome == 'failure' }}
      with:
        name: "Build log"
        path: build.log

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [build]
    steps:
      # Set up the variables that we will use to build the release name
      - name: Set release variables
        id: vars
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d-%Hh%Mm%Ss')"
          echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      # Retrieve the PDF
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: "documents"

      # Create a new release with the documents as assets
      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'documents-${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha8 }}'
          name: 'Documents (version ${{ steps.vars.outputs.date }})'
          gzip: false
          files: >
            masters_dissertation.pdf
            masters_defense.pdf
            EIAH_2023_article.pdf 
