name: "Build and release"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    # Set up the build environment
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Install nix
      uses: cachix/install-nix-action@v16
    - name: Setup cachix
      uses: cachix/cachix-action@v10
      with:
        name: dettorer
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    # Build, publish to cachix and retrieve the PDF in the current directory
    - name: Build the PDF
      id: nix-build
      run: nix build
    - name: Publish the build result to cachix
      run: nix path-info --recursive | cachix push dettorer
    - name: Retrieve the PDF
      run: |
        cp $(nix path-info)/Paul_Hervot_M2_dissertation.pdf .

    # Upload the PDF as job artifact
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "Dissertation PDF"
        path: |
          Paul_Hervot_M2_dissertation.pdf

    # If the build failed, upload the build log instead
    - name: Retrieve build log
      if: ${{ always() && steps.nix-build.outcome == 'failure' }}
      run: nix log > build.log
    - name: Upload the build log artifact
      uses: actions/upload-artifact@v2
      if: ${{ always() && steps.nix-build.outcome == 'failure' }}
      with:
        name: "Build log"
        path: build.log

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [build]
    steps:
      # Set up the variables that we will use to build the release name
      - name: Set release variables
        id: vars
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d-%Hh%Mm%Ss')"
          echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      # Retrieve the PDF
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: "Dissertation PDF"

      # Create a new release to host the PDF
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
        with:
          tag_name: 'dissertation-${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha8 }}'
          release_name: 'Dissertation (version ${{ steps.vars.outputs.date }})'
          draft: false
          prerelease: false

      # Attach the PDF to the release
      - name: Attach PDF
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          upload_url: '${{ steps.create_release.outputs.upload_url }}'
          asset_path: ./Paul_Hervot_M2_dissertation.pdf
          asset_name: Paul_Hervot_M2_dissertation.pdf
          asset_content_type: application/pdf
